# Generated by Django 5.0.1 on 2024-01-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='hp',
            field=models.IntegerField(max_length=100, verbose_name='KM'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='year',
            field=models.IntegerField(max_length=100, verbose_name='Rok'),
        ),
    ]
