# Generated by Django 5.0.1 on 2024-01-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_applications_hp_alter_applications_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='hp',
            field=models.CharField(max_length=100, verbose_name='KM'),
        ),
    ]
