# Generated by Django 5.0.1 on 2024-01-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_applications_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name': 'Wniosek', 'verbose_name_plural': 'Wnioski'},
        ),
        migrations.AlterField(
            model_name='applications',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
    ]
