# Generated by Django 5.0.1 on 2024-01-30 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_applications_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='from_who',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Od kogo'),
        ),
    ]
