# Generated by Django 5.0.1 on 2024-01-31 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_applications_from_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='from_who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Od kogo'),
        ),
    ]
