# Generated by Django 5.0.1 on 2024-02-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_applications_from_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, max_length=20, verbose_name='Numer kontaktowy'),
        ),
    ]
