# Generated by Django 5.0.1 on 2024-05-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
