# Generated by Django 5.0.1 on 2024-05-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_applications_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Wykonany'),
        ),
    ]
