# Generated by Django 5.0.1 on 2024-01-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='zdjecia/')),
                ('header', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nagłówek')),
                ('date', models.DateTimeField(auto_now=True)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Treść')),
            ],
            options={
                'verbose_name': 'Wiadomości',
                'verbose_name_plural': 'Wiadomości',
            },
        ),
    ]
