# Generated by Django 5.0.1 on 2024-02-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Humor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='zdjecia/')),
                ('header', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nagłówek')),
                ('date', models.DateTimeField(auto_now=True)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Treść')),
            ],
            options={
                'verbose_name': 'Ciekawą sytuację',
                'verbose_name_plural': 'Sytuacje',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='zdjecia/')),
                ('header', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nagłówek')),
                ('date', models.DateTimeField(auto_now=True)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Treść')),
            ],
            options={
                'verbose_name': 'Promocję',
                'verbose_name_plural': 'Promocje',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Nowość', 'verbose_name_plural': 'Nowośći'},
        ),
    ]
